// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: items.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (id, product_name, product_description, price, in_stock, updated_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, product_name, product_description, price, in_stock, updated_at, product_image
`

type CreateItemParams struct {
	ID                 uuid.UUID
	ProductName        string
	ProductDescription string
	Price              int32
	InStock            bool
	UpdatedAt          time.Time
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, createItem,
		arg.ID,
		arg.ProductName,
		arg.ProductDescription,
		arg.Price,
		arg.InStock,
		arg.UpdatedAt,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.ProductName,
		&i.ProductDescription,
		&i.Price,
		&i.InStock,
		&i.UpdatedAt,
		&i.ProductImage,
	)
	return i, err
}

const getItems = `-- name: GetItems :many
SELECT product_name, product_description, price, in_stock FROM items
`

type GetItemsRow struct {
	ProductName        string
	ProductDescription string
	Price              int32
	InStock            bool
}

func (q *Queries) GetItems(ctx context.Context) ([]GetItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, getItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetItemsRow
	for rows.Next() {
		var i GetItemsRow
		if err := rows.Scan(
			&i.ProductName,
			&i.ProductDescription,
			&i.Price,
			&i.InStock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetItems = `-- name: ResetItems :exec
TRUNCATE items
`

func (q *Queries) ResetItems(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetItems)
	return err
}
