// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Item struct {
	ID                 uuid.UUID
	ProductName        string
	ProductDescription string
	Price              int32
	InStock            bool
	UpdatedAt          time.Time
	ProductImage       string
}

type Post struct {
	ID        int32
	Title     string
	Body      string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
}

type User struct {
	ID             uuid.UUID
	Username       string
	Email          string
	HashedPassword string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
